export const metadata = {
  title: 'MyHouse',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="shortcut icon" href="logo.svg" type="image/svg" />
      </head>
      <body>{children}</body>
    </html>
  )
}
