import '../styles/globals.css';
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: 'MyHouse',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="shortcut icon" href="logo.svg" type="image/svg" />
      </head>
      <body>
        {children}
        <Toaster position="top-center" toastOptions={{style: { padding: '20px', fontSize: '1.6rem' }}}/>
      </body>
    </html>
  )
}
